// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Generates step-by-step instructions from a recipe.
 *
 * - generateSteps - A function that handles the generation of step-by-step instructions from a recipe.
 * - GenerateStepsInput - The input type for the generateSteps function.
 * - GenerateStepsOutput - The return type for the generateSteps function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateStepsInputSchema = z.object({
  recipe: z.string().describe('The recipe to generate step-by-step instructions from.'),
});
export type GenerateStepsInput = z.infer<typeof GenerateStepsInputSchema>;

const GenerateStepsOutputSchema = z.object({
  steps: z.string().describe('The step-by-step instructions for the recipe.'),
});
export type GenerateStepsOutput = z.infer<typeof GenerateStepsOutputSchema>;

export async function generateSteps(input: GenerateStepsInput): Promise<GenerateStepsOutput> {
  return generateStepsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateStepsPrompt',
  input: {schema: GenerateStepsInputSchema},
  output: {schema: GenerateStepsOutputSchema},
  prompt: `You are an expert chef who can break down a recipe into step-by-step instructions.

  Recipe: {{{recipe}}}

  Generate step-by-step instructions for the above recipe:
  `,
});

const generateStepsFlow = ai.defineFlow(
  {
    name: 'generateStepsFlow',
    inputSchema: GenerateStepsInputSchema,
    outputSchema: GenerateStepsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
